### PR TITLE
removing clause for microsoft and apple

### PR DESCRIPTION
**Pull request by lachellel**

### CODE REVIEW

**Comment by lachellel** [comment]
@ryancdickson @djpackham 

I hadn't submitted the PR for this edit.  Can you double check my edits please?

**Comment by ryancdickson** [comment]
Change looks good.

Did notice a few other things:
- Should we change...
     - "There are two Trust stores to consider for your network domain:" to "There are two **t**rust stores to consider for your network domain:"
     - all instances of "certificate authority" to "certification authority"?
     -  "Your workstations and server also need to be able to trust the network domain." to " Your workstations and server**s** also need to be able to trust the network domain."
     - "You want to add COMMON root certificate to a Group Policy Object to publish COMMON as a trusted root for ALL the devices and user objects." to .... "You want to add **the** COMMON root certificate to a Group Policy Object to publish **it** as a trusted root for ALL the devices and user objects.

There are a few smaller word choice updates I could also make (nitpicking).

Want me to take care of these @lachellel ?

**Comment by lachellel** [comment]
@ryancdickson sure - add a few more updates!

Don't nitpick too much.

**Comment by ryancdickson** [comment]
Done!

**Pull request merged**
