### PR TITLE
O365 Playbook

### PR DESCRIPTION
**Pull request by bob-fontana**
O365 playbook was rewritten after we performed QA on the procedures.  So, merging two forks plus adding new image files.

 .gitignore
https://github.com/GSA/piv-guides/compare/staging...bob-fontana:staging#diff-6ade0e56daaa2d56895486b876d8a2b
https://github.com/GSA/piv-guides/compare/staging...bob-fontana:staging#diff-8bae4c8af86e5b8030cc406483542be
https://github.com/GSA/piv-guides/compare/staging...bob-fontana:staging#diff-1a7bcae52228386f3d8542bb1ffd165285
https://github.com/GSA/piv-guides/compare/staging...bob-fontana:staging#diff-1a7bcae52228386f3d8542bb1ffd1652
https://github.com/GSA/piv-guides/compare/staging...bob-fontana:staging#diff-aca9bff65f362071e70e96395ddee16a
https://github.com/GSA/piv-guides/compare/staging...bob-fontana:staging#diff-9bec6270deca433f134dd2e2758e837c

### CODE REVIEW

**Comment by lachellel** [comment]
reopened 

@bob-fontana you closed the PR request.  does this mean you don't want to submit the PR and are going to resubmit another one?  

I reopened to capture the comments.

**Comment by bob-fontana** [comment]
@lachellel I clicked the Close without realizing what it does.

**Comment by bob-fontana** [comment]
@lachellel Also, does this mean I need to resubmit?

**Comment by lachellel** [comment]
@bob-fontana nope, no need to resubmit

I will QA and list the top issues here in the PR.  If needed, we can open a new branch and iterate.

**Comment by lachellel** [comment]
we'll open issues for updates

accepting PR

**Pull request merged**
