### PR TITLE
Add a link to the FAQ in the sidebar

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by lachellel** [comment]
@alex 

I'm going to apply these changes _post_ style merges #72 
...your last PR was against _gh-pages_ instead of _staging_ and I merged - so the FAQ md was not sync'd
It was my fault.  Will be fixing as we prep for Federalist deployment.

**Comment by alex** [comment]
Ok! Let me know if there's anything I can do to make it easier for you.

**Comment by indrajit-gsa** [comment]
@lachellel -- This is an old pull request. Is this still relevant? Is there an FAQ section? Should we discard this one?

**Comment by indrajit-gsa** [comment]
Closing this old pull request. It does not have the proper FAQ materials for publishing.

**Pull request closed without merging**
