### PR TITLE
remove APL references

### PR DESCRIPTION
**Pull request by lachellel**
Updated for #67 and agency request

### CODE REVIEW

**Comment by lachellel** [comment]
@djpackham 

review please?

**Comment by rt-smithee** [comment]
If you use a card reader and you enter your PIN you probably want to be careful about whether or not you are using Secure PIN Entry.   If there's supposed to be pc-connected smartcard reader usage guidance in this, does it perhaps need additional text...

**Comment by djpackham** [comment]
@lachellel 

The update looks good to me. I do agree with @rt-smithee that there is additional guidance we can add as part of another pull request for selecting an ideal USB type smart card reader. Is Secure PIN Entry part of a standard, like ISO 7816, we could reference?

**Comment by lachellel** [comment]
this PR is simply to remove the APL reference 
an issue can be opened for when to address secure pin entry

**Pull request merged**
