### PR TITLE
Procedures to enable PIV for SSH to UNIX-like system from UNIX/Linux computer

### PR DESCRIPTION
**Pull request by clstmbrly**
@lachellel These procedures are based on another agency's procedures (NIH?).  Testing is in process to validate the procedures.

### CODE REVIEW

**Comment by rt-smithee** [comment]
Nice.  Some comments.  This assumes you have loaded the OpenSC package such that their PKCS-11 shared library is installed and available to conventional users.  Steps 5 and 7 render curiously on my chrome/windows workstation (but as far as I can tell the steps are ok, just rendered with crushed pointy brackets.

Now that you've mentioned opensc perhaps also somewhere it might mention one can do "opensc-tool --list-readers" to confirm there's a reader and "opensc-tool --atr" to confirm it knows there's a card present.  (those are my go-to commands to start with, much more can be done with opensc-related command line tools...)

**Comment by godadada** [comment]
@lachellel   @rt-smithee 
The document has assumption stated as ‘prerequisite’ that user has done login to Linux console using PIV, when user has done access of card reader and car itself.  There may be need to repeat card reader access and card access commands in doing ssh using PIV, or to combine the console login document with ssh document. But decision has to be made to make the change. We have similar issue with Windows/Mac version.

**Comment by rt-smithee** [comment]
I mis-read the intro.  In the Hardware Requirements it does state the assumption cards are already working.  Elsewhere in this project there is discussion of middleware to use, Perhaps my "opensc" comment applies to that.

**Comment by clstmbrly** [comment]
@lachellel Two changes need to be made to command line instructions in these procedures.  I will resubmit the Pull Request.

**Comment by clstmbrly** [comment]
Two corrections needed to command line instructions.

**Pull request closed without merging**
