### PR TITLE
Recommended updates to managing trusted roots page

### PR DESCRIPTION
**Pull request by connellyt**
Added some additional information on managing the AD trust stores, as well as some clarifications.

### CODE REVIEW

**Comment by lachellel** [comment]
Thanks @connellyt 

General edits look good!   One question:

- Why suggest removing the Principal Name vs AltSecID option / table?

For altSecID and issuer/subject mapping - in the non-bridged paths, we've confirmed that only a root works.  All issuing CAs aren't needed.  I recently worked with an agency colleague who had the altsecid only enabled and only common in the ntauth.  _I can't confirm if this works for the CAs signed by bridge(s)._

**Comment by connellyt** [comment]
Perhaps I don't understand your comment on the altSecID and issuer/subject mapping with only a root, and I obviously can't speak to the experience you helped that agency work through.  However, we're currently using altSecID and subject mapping without Common in NTAuth, with no issues.  If we remove the Issuing CA from NTAuth and add only Common, smart card logon breaks.  All MS documentation on the configuration doesn't seem to indicate putting the Root CA in NTAuth is necessary.

Obviously, not all issuing CAs need to be in NTAuth (and not even the full path) - just the ones you want to use to associate certificates to users.

**Comment by lachellel** [comment]
@connellyt I really wish I could find the older diagrams for logic flows.  :persevere:

> However, we're currently using altSecID and subject mapping without Common in NTAuth, with no issues. 
>All MS documentation on the configuration doesn't seem to indicate putting the Root CA in NTAuth is necessary.

Publishing the issuing CA(s) certs will always work.  

>If we remove the Issuing CA from NTAuth and add only Common, smart card logon breaks. 

And **disableUPN mapping** is enabled on the domain?  If so - that's interesting.   I'll look into the versions again and see what I can find!

The pro for only including Common is **less overhead** for those **few agencies** that can do this method.

**Comment by connellyt** [comment]
Correct - we have UPN mapping disabled.

**Comment by lachellel** [comment]
@connellyt 

I'm going to merge this edit.  
For the altsecid mapping using issuer/subject, I know this edit doesn't apply to 2016 **but** I will trust you for later versions.  Part of the processing logic flow is detailed here:

-  https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration#client-certificate-requirements-and-mappings
- See "Certificate Processing Logic" diagram, and whether NT Auth policy applies

Within that full page, there is one slight discrepancy that can cause confusion for agencies: the reference to "if a UPN is in the cert, then..."

**Pull request merged**
